name: 'Hello World'
description: 'Greet someone and record the time'
# inputs:
#   repo-token:
#     description: 'bob'
#     required: true
#     default: 'bob'
outputs:
  pull_requests:
    description: a list of dependabot repos
runs:
  using: 'node12'
  main: 'dist/index.js'